### ISSUE TITLE
Crash Report on Android 12

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [RailwayStations/RSAndroidApp#311]
Crash Report on Android 12 but i dont know why

### App information
* ID: de.bahnhoefe.deutschlands.bahnhofsfotos
* Version: 65 13.2.0

### Device information
* Brand: samsung
* Device: o1s
* Model: SM-G991B
* Id: SP1A.210812.016
* Product: o1sxeea

### Firmware
* SDK: 31
* Release: 12
* Incremental: G991BXXU5CVGB

### Cause of error
```java
Exception in thread "LayerManager": java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1396)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:455)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:413)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:544)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.mapsforge.Cluster.getTitle(Cluster.java:64)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.mapsforge.ClusterMarker.draw(ClusterMarker.java:115)
	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)

```

**Comment by pstorch** [comment]
Thanks for reporting. I'll look into it.
