### ISSUE TITLE
Race Condition in MapsActivity

### ISSUE THREAD

**Issue by pelzvieh** [RailwayStations/RSAndroidApp#37]
> Problematische Geräte
> LG G3 (g3) - Android 4.4
> 
> Ausnahmen
> java.lang.RuntimeException: Unable to pause activity {de.bahnhoefe.deutschlands.bahnhofsfotos/de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity}: java.lang.IllegalStateException: GoogleApiClient is not connected yet.

Klingt so, als könnte man dasTracking pausieren, bevor es richtig initialisiert ist!

`FATAL EXCEPTION: main
 Process: de.bahnhoefe.deutschlands.bahnhofsfotos, PID: 10266
 java.lang.RuntimeException: Unable to pause activity {de.bahnhoefe.deutschlands.bahnhofsfotos/de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity}: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3079)
 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3034)
 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3729)
 	at android.app.ActivityThread.access$900(ActivityThread.java:142)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1209)
 	at android.os.Handler.dispatchMessage(Handler.java:102)
 	at android.os.Looper.loop(Looper.java:136)
 	at android.app.ActivityThread.main(ActivityThread.java:5118)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:515)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
 	at com.google.android.gms.internal.zzpw.zzd(Unknown Source)
 	at com.google.android.gms.internal.zzqa.zzd(Unknown Source)
 	at com.google.android.gms.internal.zzpy.zzd(Unknown Source)
 	at com.google.android.gms.location.internal.zzd.removeLocationUpdates(Unknown Source)
 	at de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity.stopLocationUpdates(MapsActivity.java:381)
 	at de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity.onPause(MapsActivity.java:291)
 	at android.app.Activity.performPause(Activity.java:5379)
 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3065)
 	... 12 more
 `

**Comment by androidoma** [comment]
Done
