### ISSUE TITLE
Absturz beim Drehen bei "In der Nähe"

### ISSUE THREAD

**Issue by khgdrn** [RailwayStations/RSAndroidApp#43]
Hochformat
Starte die App.
Wechsel zu "In der Nähe"
Drehe ins Querformat
Absturz
[issue_absturz.zip](https://github.com/RailwayStations/RSAndroidApp/files/1002314/issue_absturz.zip)

**Comment by pstorch** [comment]
Ich sehe diesen Fehler:

```
FATAL EXCEPTION: main
Process: de.bahnhoefe.deutschlands.bahnhofsfotos, PID: 14754
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.bahnhoefe.deutschlands.bahnhofsfotos/de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity}: android.view.InflateException: Binary XML file line #3: Binary XML file line #3: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2728)
...
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.Toolbar$SavedState
...
at de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity.onCreate(MapsActivity.java:81)
...
```

Irgendwie könnte die nested Toolbar das Problem verursachen:
https://stackoverflow.com/questions/36811037/class-not-found-when-unmarshalling-android-support-v7-widget-toolbarsavedstate

**Comment by pstorch** [comment]
Ich habs
