### ISSUE TITLE
Karte flackert und zeigt nichts an, bis man sie bewegt

### ISSUE THREAD

**Issue by androidoma** [RailwayStations/RSAndroidApp#95]
08-07 18:05:31.300 17782-17782/de.bahnhoefe.deutschlands.bahnhofsfotos E/MapsActivity: Error registering LocationManager
    java.lang.RuntimeException: No Permission for ACCESS_FINE_LOCATION
        at de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity.registerLocationManager(MapsActivity.java:478)
        at de.bahnhoefe.deutschlands.bahnhofsfotos.MapsActivity.onResume(MapsActivity.java:415)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:7107)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3785)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3851)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3052)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by pstorch** [comment]
Das flackern und die leere Karte kann bei vielem Rumscrollen und Rein- und Rauszoomen manchmal noch vorkommen. Komplett gelöst ist es noch nicht, aber die Exception kommt nicht mehr vor.
